// AWWW YEAH, IT'S WRITTEN ALL IN CAPS, SO YOU KNOW IT'S IMPORTANT!
// THIS IS WHERE YOU CAN MODIFY THINGS... and... uhhhh... AWW YEAH!

//-----------------------------------------------------------------


//LUA

//DOLMEXICA SUPPORTS THREE TYPES OF LUA, THE ONE KALLISTIOS COMES WITH,
//THE NEWEST VERSION, OR NONE AT ALL. YOU MUST CHOOSE YOUR VERSION HERE.
//JUST COMMENT OUT THE OTHER TWO. 

//------SETTINGS AREA START

//#define LUA_VERSION_NONE 	//YOU'RE NOT USING LUA AT ALL?!
//#define LUA_VERSION_KOS  	//YOU'RE USING THE VERSION COMING WITH KOS?! (CHECK CONFIG.MAKEFILE TO INCLUDE THE LIBRARY)
#define LUA_VERSION_502 	//YOU'RE USING VERSION 5.2, WHICH IS ALSO WHAT THE PRECOMPILED VERSION DOES?! (CHECK CONFIG.MAKEFILE TO INCLUDE THE LIBRARY) 

//------SETTINGS AREA STOP

//IF YOU ARE USING VERSION 5.2 (LUA_VERSION_502), 
//YOU MUST INCLUDE THE THREE PATHS OF THE HEADER FILES OF 
//THAT VERSION AS WELL, OTHERWISE, COMMENT THEM OUT.

//------SETTINGS AREA START

#define LUA_HEADER_PATH 	"/home/captaindc/dc/kos-ports/luanew/src/lua.h" 	//lua.h
#define LUA_HEADER_LIB_PATH	"/home/captaindc/dc/kos-ports/luanew/src/lualib.h"  	//lualib.h
#define LUA_HEADER_AUX_PATH	"/home/captaindc/dc/kos-ports/luanew/src/lauxlib.h"	//lauxlib.h

//------SETTINGS AREA STOP


//SD-CARD

//OPTIONS RELATED TO THE D-ENGINE'S SD-CARD SUPPORT!

//------SETTINGS AREA START

#define DOLMEXICA_SD		//YOU'RE USING THE SD-CARD LIBRARY THAT COMES ALONG WITH THE D-ENGINE?! (CHECK CONFIG.MAKEFILE TO INCLUDE THE LIBRARY)
//#define DOLMEXICA_SD_NONE	//YOU'RE DISABLING SD-CARD SUPPORT?!

//------SETTINGS AREA STOP


//DEBUG

//THIS HERE IS ONLY STUFF RELATED TO DEVELOPMENT, NONE OF THIS SHOULD BE 
//IN A FINAL BUILD.

//------SETTINGS AREA START

//#define DOLMEXICA_DEBUG_BORDERCOLOR

//------SETTINGS AREA STOP




